# Generated by Django 5.2.11 on 2026-03-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('user', 'Agent / Employé')], default='admin', max_length=20),
        ),
    ]
