# Generated by Django 5.2.11 on 2026-03-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_entreprise_has_branches_succursale'),
        ('users', '0002_add_role_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Agent / Employé')], default='user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_succursale', models.ForeignKey(blank=True, help_text="Succursale par défaut si l'entreprise a des succursales.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_memberships', to='stock.succursale')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stock.entreprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entreprise_id', 'user_id', 'id'],
                'unique_together': {('user', 'entreprise')},
            },
        ),
        migrations.CreateModel(
            name='UserBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.membership')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_branches', to='stock.succursale')),
            ],
            options={
                'ordering': ['succursale_id', 'membership_id', 'id'],
                'unique_together': {('membership', 'succursale')},
            },
        ),
    ]
