# Generated by Django 5.2.11 on 2026-03-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_backfill_memberships_from_user_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='entreprise',
        ),
    ]
