# Generated by Django 5.2.11 on 2026-03-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('nom_scientifique', models.CharField(max_length=100)),
                ('nom_commercial', models.CharField(blank=True, max_length=100, null=True)),
                ('article_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('emplacement', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('symbole', models.CharField(max_length=10)),
                ('est_principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
            },
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_op', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('secteur', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nif', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('EN_CREDIT', 'En crédit'), ('PAYEE', 'Payée')], default='PAYEE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SousTypeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte', models.PositiveIntegerField(default=0)),
                ('seuilAlert', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, help_text='Date limite de paiement', null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('PAYEE', 'Payée'), ('RETARD', 'En retard')], default='EN_COURS', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='stock.client')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='stock.devise')),
            ],
            options={
                'verbose_name': 'Dette client',
                'verbose_name_plural': 'Dettes clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='devise',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devises', to='stock.entreprise'),
        ),
        migrations.CreateModel(
            name='LigneEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('quantite_restante', models.PositiveIntegerField(default=0, help_text='Quantité encore disponible dans ce lot (FIFO)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire", max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, help_text="Prix de vente unitaire défini à l'entrée", max_digits=10)),
                ('date_expiration', models.DateField(blank=True, help_text="Date d'expiration du produit (optionnelle)", null=True)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('seuil_alerte', models.PositiveIntegerField(default=0, help_text="Seuil d'alerte pour cet article")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.article')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligneentrees', to='stock.devise')),
                ('entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.entree')),
            ],
            options={
                'ordering': ['date_entree', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LigneSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, help_text='Prix réellement encaissé (peut différer du prix de vente du lot en cas de promotion/réduction)', max_digits=10)),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='stock.article')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignesorties', to='stock.devise')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficeLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendue', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefice_unitaire', models.DecimalField(decimal_places=2, help_text='Prix vente - Prix achat', max_digits=10)),
                ('benefice_total', models.DecimalField(decimal_places=2, help_text='Bénéfice total pour cette quantité', max_digits=12)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('lot_entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefices', to='stock.ligneentree')),
                ('ligne_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefices_lots', to='stock.lignesortie')),
            ],
            options={
                'verbose_name': 'Bénéfice par lot',
                'verbose_name_plural': 'Bénéfices par lot',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='LigneSortieLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(help_text='Quantité prélevée de ce lot')),
                ('prix_achat', models.DecimalField(decimal_places=2, help_text="Prix d'achat du lot (copié)", max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, help_text='Prix de vente du lot (copié)', max_digits=10)),
                ('ligne_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_utilises', to='stock.lignesortie')),
                ('lot_entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties_utilisees', to='stock.ligneentree')),
            ],
            options={
                'verbose_name': 'Lot utilisé dans sortie',
                'verbose_name_plural': 'Lots utilisés dans sorties',
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('motif', models.TextField()),
                ('moyen', models.CharField(blank=True, help_text='Ex: Cash, Mobile Money, Chèque', max_length=30, null=True)),
                ('reference_piece', models.CharField(blank=True, max_length=100, null=True)),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse', to='stock.devise')),
                ('entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvement_caisse', to='stock.entree')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaiementDette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('moyen', models.CharField(blank=True, help_text='Ex: Cash, Mobile Money, Chèque', max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='stock.detteclient')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_dettes', to='stock.devise')),
            ],
            options={
                'verbose_name': 'Paiement de dette',
                'verbose_name_plural': 'Paiements de dettes',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
