# Generated by Django 5.2.11 on 2026-03-02 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementdette',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_dettes_effectues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sortie',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client associé à cette sortie (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties', to='stock.client'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='devise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='stock.devise'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='sortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvement_caisse', to='stock.sortie'),
        ),
        migrations.AddField(
            model_name='lignesortie',
            name='sortie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.sortie'),
        ),
        migrations.AddField(
            model_name='detteclient',
            name='sortie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dette', to='stock.sortie'),
        ),
        migrations.AddField(
            model_name='article',
            name='sous_type_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.soustypearticle'),
        ),
        migrations.AddField(
            model_name='stock',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.article'),
        ),
        migrations.AddField(
            model_name='soustypearticle',
            name='type_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_types', to='stock.typearticle'),
        ),
        migrations.AddField(
            model_name='article',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.unite'),
        ),
        migrations.AlterUniqueTogether(
            name='devise',
            unique_together={('sigle', 'entreprise')},
        ),
        migrations.AddIndex(
            model_name='ligneentree',
            index=models.Index(fields=['article', 'date_entree'], name='stock_ligne_article_e99d66_idx'),
        ),
        migrations.AddIndex(
            model_name='lignesortielot',
            index=models.Index(fields=['ligne_sortie', 'lot_entree'], name='stock_ligne_ligne_s_c7f781_idx'),
        ),
    ]
