# Generated by Django 5.2.11 on 2026-03-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entreprises/logos/'),
        ),
    ]
