# Generated by Django 5.2.11 on 2026-03-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_entreprise_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='slogan',
            field=models.CharField(blank=True, help_text="Devise ou slogan de l'entreprise (affiché dans l'en-tête des rapports)", max_length=255, null=True),
        ),
    ]
