# Generated by Django 5.2.11 on 2026-03-18 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_add_entreprise_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='has_branches',
            field=models.BooleanField(default=False, help_text='Active la gestion par succursales (branches).'),
        ),
        migrations.CreateModel(
            name='Succursale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succursales', to='stock.entreprise')),
            ],
            options={
                'ordering': ['entreprise_id', 'nom', 'id'],
                'unique_together': {('entreprise', 'nom')},
            },
        ),
    ]
