# Generated by Django 5.2.11 on 2026-03-18 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_entreprise_has_branches_succursale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='article',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='stock.succursale'),
        ),
        migrations.AddField(
            model_name='client',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='client',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='stock.succursale'),
        ),
        migrations.AddField(
            model_name='detteclient',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dettes_clients', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='detteclient',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dettes_clients', to='stock.succursale'),
        ),
        migrations.AddField(
            model_name='entree',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrees', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='entree',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrees', to='stock.succursale'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse', to='stock.succursale'),
        ),
        migrations.AddField(
            model_name='paiementdette',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_dettes', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='paiementdette',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_dettes', to='stock.succursale'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='stock.succursale'),
        ),
        migrations.AddField(
            model_name='soustypearticle',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_type_articles', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='soustypearticle',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_type_articles', to='stock.succursale'),
        ),
        migrations.AddField(
            model_name='typearticle',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_articles', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='typearticle',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_articles', to='stock.succursale'),
        ),
        migrations.AddField(
            model_name='unite',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='stock.entreprise'),
        ),
        migrations.AddField(
            model_name='unite',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='stock.succursale'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['entreprise_id'], name='stock_artic_entrepr_3aa35b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['succursale_id'], name='stock_artic_succurs_93f236_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_artic_entrepr_92b06b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['entreprise_id'], name='stock_clien_entrepr_f00fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['succursale_id'], name='stock_clien_succurs_353de2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_clien_entrepr_2611a1_idx'),
        ),
        migrations.AddIndex(
            model_name='detteclient',
            index=models.Index(fields=['entreprise_id'], name='stock_dette_entrepr_c39c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='detteclient',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_dette_entrepr_61d8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='entree',
            index=models.Index(fields=['entreprise_id'], name='stock_entre_entrepr_83a12f_idx'),
        ),
        migrations.AddIndex(
            model_name='entree',
            index=models.Index(fields=['succursale_id'], name='stock_entre_succurs_fd439a_idx'),
        ),
        migrations.AddIndex(
            model_name='entree',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_entre_entrepr_98cbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['entreprise_id'], name='stock_mouve_entrepr_bd2459_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['succursale_id'], name='stock_mouve_succurs_0d3ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_mouve_entrepr_c4f4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementdette',
            index=models.Index(fields=['entreprise_id'], name='stock_paiem_entrepr_0ffc77_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementdette',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_paiem_entrepr_c82dab_idx'),
        ),
        migrations.AddIndex(
            model_name='sortie',
            index=models.Index(fields=['entreprise_id'], name='stock_sorti_entrepr_479496_idx'),
        ),
        migrations.AddIndex(
            model_name='sortie',
            index=models.Index(fields=['succursale_id'], name='stock_sorti_succurs_55beb9_idx'),
        ),
        migrations.AddIndex(
            model_name='sortie',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_sorti_entrepr_ac624b_idx'),
        ),
        migrations.AddIndex(
            model_name='soustypearticle',
            index=models.Index(fields=['entreprise_id'], name='stock_soust_entrepr_c99e44_idx'),
        ),
        migrations.AddIndex(
            model_name='soustypearticle',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_soust_entrepr_bb2684_idx'),
        ),
        migrations.AddIndex(
            model_name='typearticle',
            index=models.Index(fields=['entreprise_id'], name='stock_typea_entrepr_0a6efa_idx'),
        ),
        migrations.AddIndex(
            model_name='typearticle',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_typea_entrepr_9c07da_idx'),
        ),
        migrations.AddIndex(
            model_name='unite',
            index=models.Index(fields=['entreprise_id'], name='stock_unite_entrepr_550fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='unite',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_unite_entrepr_40ae77_idx'),
        ),
    ]
