# Generated by Django 5.2.11 on 2026-03-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_add_tenant_fields_to_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Si vrai, client priorisé dans les rapports (ex. dettes) par défaut.', verbose_name='Client spécial'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['entreprise_id', 'is_special'], name='stock_clien_entrepr_513664_idx'),
        ),
    ]
