# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0016_retry_ensure_mouvementcaisse_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(help_text="Code interne unique par entreprise (généré automatiquement si vide).", max_length=40)),
                ("nom", models.CharField(max_length=255)),
                ("telephone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("pays", models.CharField(blank=True, max_length=100, null=True)),
                ("nif", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entreprise",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fournisseurs", to="stock.entreprise"),
                ),
                (
                    "succursale",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="fournisseurs", to="stock.succursale"),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "ordering": ["nom", "id"],
                "unique_together": {("entreprise", "code")},
            },
        ),
        migrations.AddIndex(
            model_name="fournisseur",
            index=models.Index(fields=["entreprise_id", "nom"], name="stock_fournisseur_entreprise_nom_idx"),
        ),
        migrations.AddIndex(
            model_name="fournisseur",
            index=models.Index(fields=["entreprise_id", "is_active"], name="stock_fournisseur_entreprise_active_idx"),
        ),
        migrations.AddIndex(
            model_name="fournisseur",
            index=models.Index(fields=["entreprise_id", "code"], name="stock_fournisseur_entreprise_code_idx"),
        ),
        migrations.AddIndex(
            model_name="fournisseur",
            index=models.Index(fields=["entreprise_id", "created_at"], name="stock_fournisseur_entreprise_created_idx"),
        ),
    ]
