# Generated by Django 5.2.11 on 2026-03-27 01:00

import django.db.models.deletion
from django.db import migrations, models


def forwards_fill_cliententreprise(apps, schema_editor):
    Client = apps.get_model("stock", "Client")
    ClientEntreprise = apps.get_model("stock", "ClientEntreprise")
    for c in Client.objects.all().iterator():
        eid = getattr(c, "entreprise_id", None)
        if eid:
            ClientEntreprise.objects.get_or_create(
                client_id=c.pk,
                entreprise_id=eid,
                defaults={
                    "succursale_id": getattr(c, "succursale_id", None),
                    "is_special": bool(getattr(c, "is_special", False)),
                },
            )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0020_client_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientEntreprise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_special",
                    models.BooleanField(
                        default=False,
                        help_text="Priorité dans les rapports (dettes, etc.) pour ce client dans cette entreprise.",
                        verbose_name="Client spécial",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_entreprise",
                        to="stock.client",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_clients",
                        to="stock.entreprise",
                    ),
                ),
                (
                    "succursale",
                    models.ForeignKey(
                        blank=True,
                        help_text="Succursale de rattachement pour ce client dans cette entreprise (optionnel).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liens_clients",
                        to="stock.succursale",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "entreprise")},
            },
        ),
        migrations.AddIndex(
            model_name="cliententreprise",
            index=models.Index(fields=["entreprise_id", "client_id"], name="stock_clien_entrepr_405f31_idx"),
        ),
        migrations.AddIndex(
            model_name="cliententreprise",
            index=models.Index(fields=["client_id"], name="stock_clien_client__217599_idx"),
        ),
        migrations.AddIndex(
            model_name="cliententreprise",
            index=models.Index(fields=["entreprise_id", "is_special"], name="stock_clien_entrepr_1b06f7_idx"),
        ),
        migrations.RunPython(forwards_fill_cliententreprise, backwards_noop),
        migrations.RemoveIndex(
            model_name="client",
            name="stock_clien_entrepr_f00fc4_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="stock_clien_succurs_353de2_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="stock_clien_entrepr_2611a1_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="stock_clien_entrepr_513664_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="stock_client_entreprise_email_idx",
        ),
        migrations.RemoveField(
            model_name="client",
            name="entreprise",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_special",
        ),
        migrations.RemoveField(
            model_name="client",
            name="succursale",
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="stock_clien_email_b7739e_idx"),
        ),
    ]
