# Generated by Django 5.2.11 on 2026-03-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_client_entreprise_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='motif',
            field=models.TextField(blank=True, default='', help_text='Libellé / motif du mouvement.'),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='moyen',
            field=models.CharField(blank=True, help_text='Ex. : Cash, Mobile Money, Chèque (optionnel).', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='motif',
            field=models.CharField(blank=True, help_text='Motif / commentaire de la sortie (hors caisse).', max_length=255),
        ),
    ]
