# Generated by Django 5.2.11 on 2026-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_decimal_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficelot',
            name='benefice_total',
            field=models.DecimalField(decimal_places=5, help_text='Bénéfice total pour cette quantité', max_digits=12),
        ),
        migrations.AlterField(
            model_name='beneficelot',
            name='benefice_unitaire',
            field=models.DecimalField(decimal_places=5, help_text='Prix vente - Prix achat', max_digits=10),
        ),
        migrations.AlterField(
            model_name='beneficelot',
            name='prix_achat',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='beneficelot',
            name='prix_vente',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='beneficelot',
            name='quantite_vendue',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detailmouvementcaisse',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detteclient',
            name='montant_total',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ligneentree',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=5, help_text="Prix d'achat unitaire", max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneentree',
            name='prix_vente',
            field=models.DecimalField(decimal_places=5, help_text="Prix de vente unitaire défini à l'entrée", max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneentree',
            name='quantite',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ligneentree',
            name='quantite_restante',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Quantité encore disponible dans ce lot (FIFO)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='ligneentree',
            name='seuil_alerte',
            field=models.DecimalField(decimal_places=5, default=0, help_text="Seuil d'alerte pour cet article", max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignesortie',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Prix réellement encaissé (peut différer du prix de vente du lot en cas de promotion/réduction)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignesortie',
            name='quantite',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignesortielot',
            name='prix_achat',
            field=models.DecimalField(decimal_places=5, help_text="Prix d'achat du lot (copié)", max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignesortielot',
            name='prix_vente',
            field=models.DecimalField(decimal_places=5, help_text='Prix de vente du lot (copié)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignesortielot',
            name='quantite',
            field=models.DecimalField(decimal_places=5, help_text='Quantité prélevée de ce lot', max_digits=12),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Qte',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuilAlert',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
    ]
