# Generated by Django 5.2.11 on 2026-06-21 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_cleanup_legacy_client_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventaireSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('date_inventaire', models.DateField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20)),
                ('perimetre', models.CharField(choices=[('COMPLET', 'Catalogue complet'), ('EN_STOCK', 'Articles en stock uniquement'), ('PARTIEL', "Liste d'articles")], default='EN_STOCK', max_length=20)),
                ('type_article_filtre', models.CharField(blank=True, default='', max_length=100)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_demarrage', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_crees', to=settings.AUTH_USER_MODEL)),
                ('entree_ajustement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_ajustement_positif', to='stock.entree')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='stock.entreprise')),
                ('sortie_ajustement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_ajustement_negatif', to='stock.sortie')),
                ('succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='stock.succursale')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InventaireLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_theorique', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('stock_physique', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('ecart', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('motif_ligne', models.TextField(blank=True, default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_inventaire', to='stock.article')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventairesession')),
            ],
            options={
                'ordering': ['article__nom_scientifique', 'article_id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventairesession',
            index=models.Index(fields=['entreprise_id', 'statut'], name='stock_inven_entrepr_1b9f66_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairesession',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_inven_entrepr_efe27d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventaireligne',
            index=models.Index(fields=['session_id', 'article_id'], name='stock_inven_session_25457e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventaireligne',
            unique_together={('session', 'article')},
        ),
    ]
