# Generated by Django 5.2.11 on 2026-06-24 17:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Max, Min, Q, Sum


def migrer_sessions_legacy(apps, schema_editor):
    MouvementCaisse = apps.get_model('stock', 'MouvementCaisse')
    SessionCaisse = apps.get_model('stock', 'SessionCaisse')
    TypeCaisse = apps.get_model('stock', 'TypeCaisse')
    Entreprise = apps.get_model('stock', 'Entreprise')
    Devise = apps.get_model('stock', 'Devise')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    dette_ct_id = None
    try:
        dette_ct_id = ContentType.objects.get(app_label='stock', model='detteclient').id
    except ContentType.DoesNotExist:
        pass

    for ent in Entreprise.objects.all():
        if not TypeCaisse.objects.filter(entreprise_id=ent.id).exists():
            TypeCaisse.objects.create(
                entreprise_id=ent.id,
                libelle='Caisse principale',
                description='Créée automatiquement pour l\'historique des sessions',
                is_active=True,
            )

    groups = (
        MouvementCaisse.objects.filter(entreprise_id__isnull=False)
        .values('entreprise_id', 'succursale_id', 'devise_id')
        .annotate(nb=Count('id'), first_date=Min('date'), last_date=Max('date'))
        .filter(nb__gt=0)
    )

    seq = 0
    for g in groups:
        ent_id = g['entreprise_id']
        devise_id = g['devise_id']
        if not devise_id:
            default_dev = Devise.objects.filter(entreprise_id=ent_id, est_principal=True).first()
            if not default_dev:
                continue
            devise_id = default_dev.id

        tc = TypeCaisse.objects.filter(entreprise_id=ent_id, is_active=True).order_by('id').first()
        if not tc:
            continue

        seq += 1
        branch_id = g['succursale_id']
        movs = MouvementCaisse.objects.filter(
            entreprise_id=ent_id,
            succursale_id=branch_id,
            devise_id=devise_id,
        )
        agg = movs.aggregate(
            entrees=Sum('montant', filter=Q(type='ENTREE')),
            sorties=Sum('montant', filter=Q(type='SORTIE')),
        )
        entrees = agg['entrees'] or Decimal('0')
        sorties = agg['sorties'] or Decimal('0')
        solde = entrees - sorties

        session = SessionCaisse.objects.create(
            numero=f'LEGACY-{ent_id:04d}-{seq:05d}',
            type_caisse_id=tc.id,
            devise_id=devise_id,
            entreprise_id=ent_id,
            succursale_id=branch_id,
            ouvert_le=g['first_date'],
            cloture_le=g['last_date'],
            solde_ouverture=Decimal('0'),
            total_entrees=entrees,
            total_sorties=sorties,
            solde_theorique=solde,
            montant_physique=solde,
            ecart_montant=Decimal('0'),
            statut='CLOTUREE',
            commentaire_cloture='Session historique migrée automatiquement',
            est_legacy=True,
        )

        for mv in movs.iterator():
            cat = 'AUTRE'
            if mv.sortie_id:
                cat = 'VENTE'
            elif mv.entree_id:
                cat = 'APPROVISIONNEMENT'
            elif dette_ct_id and mv.content_type_id == dette_ct_id:
                cat = 'PAIEMENT_DETTE'
            elif mv.type == 'ENTREE':
                cat = 'ENTREE_MANUELLE'
            elif mv.type == 'SORTIE':
                cat = 'SORTIE_MANUELLE'
            MouvementCaisse.objects.filter(pk=mv.pk).update(
                session_caisse_id=session.id,
                type_caisse_id=tc.id,
                categorie=cat,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stock', '0027_inventaire_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcaisse',
            name='categorie',
            field=models.CharField(blank=True, choices=[('VENTE', 'Vente comptant'), ('PAIEMENT_DETTE', 'Paiement dette client'), ('APPROVISIONNEMENT', 'Approvisionnement payé cash'), ('DEPENSE', 'Dépense'), ('ENTREE_MANUELLE', 'Entrée manuelle'), ('SORTIE_MANUELLE', 'Sortie manuelle'), ('AJUSTEMENT_SURPLUS_CAISSE', 'Ajustement surplus caisse'), ('AJUSTEMENT_PERTE_CAISSE', 'Ajustement perte caisse'), ('AUTRE', 'Autre')], default='AUTRE', max_length=40),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='type_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='stock.typecaisse'),
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('ouvert_le', models.DateTimeField()),
                ('cloture_le', models.DateTimeField(blank=True, null=True)),
                ('solde_ouverture', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14)),
                ('total_entrees', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14)),
                ('total_sorties', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14)),
                ('solde_theorique', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('montant_physique', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('ecart_montant', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE_EN_ATTENTE_VALIDATION', 'Clôturée en attente validation écart'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=40)),
                ('commentaire_cloture', models.TextField(blank=True, default='')),
                ('est_legacy', models.BooleanField(default=False, help_text="Session créée par migration pour rattacher l'historique existant.")),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_caisse_cloturees', to=settings.AUTH_USER_MODEL)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to='stock.devise')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_caisse', to='stock.entreprise')),
                ('ouvert_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_caisse_ouvertes', to=settings.AUTH_USER_MODEL)),
                ('succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_caisse', to='stock.succursale')),
                ('type_caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to='stock.typecaisse')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-ouvert_le', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EcartCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecart', models.CharField(choices=[('SURPLUS', 'Surplus'), ('PERTE', 'Perte')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=5, help_text="Montant absolu de l'écart", max_digits=14)),
                ('statut', models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='EN_ATTENTE_VALIDATION', max_length=30)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('declare_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecarts_caisse_declares', to=settings.AUTH_USER_MODEL)),
                ('mouvement_ajustement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecart_source', to='stock.mouvementcaisse')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecarts_caisse_valides', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecart', to='stock.sessioncaisse')),
            ],
            options={
                'verbose_name': 'Écart de caisse',
                'verbose_name_plural': 'Écarts de caisse',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='session_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.sessioncaisse'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['session_caisse_id', 'date'], name='stock_mouve_session_a1deb6_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncaisse',
            index=models.Index(fields=['entreprise_id', 'succursale_id', 'statut'], name='stock_sessi_entrepr_3658b0_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncaisse',
            index=models.Index(fields=['type_caisse_id', 'devise_id', 'statut'], name='stock_sessi_type_ca_766535_idx'),
        ),
        migrations.RunPython(migrer_sessions_legacy, noop_reverse),
    ]
