# Generated by Django 5.2.11 on 2026-06-24 17:22

from django.db import migrations


CAISSE_MODELS = (
    'typecaisse',
    'sessioncaisse',
    'mouvementcaisse',
    'detailmouvementcaisse',
    'ecartcaisse',
)


def _content_types_to_caisse(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    for model in CAISSE_MODELS:
        ContentType.objects.filter(app_label='stock', model=model).update(app_label='caisse')


def _content_types_to_stock(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    for model in CAISSE_MODELS:
        ContentType.objects.filter(app_label='caisse', model=model).update(app_label='stock')


STATE_OPS = [
        migrations.RemoveField(
            model_name='ecartcaisse',
            name='declare_par',
        ),
        migrations.RemoveField(
            model_name='ecartcaisse',
            name='mouvement_ajustement',
        ),
        migrations.RemoveField(
            model_name='ecartcaisse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='ecartcaisse',
            name='valide_par',
        ),
        migrations.RemoveField(
            model_name='mouvementcaisse',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mouvementcaisse',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='mouvementcaisse',
            name='entree',
        ),
        migrations.RemoveField(
            model_name='mouvementcaisse',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='mouvementcaisse',
            name='session_caisse',
        ),
        migrations.RemoveField(
            model_name='mouvementcaisse',
            name='sortie',
        ),
        migrations.RemoveField(
            model_name='mouvementcaisse',
            name='succursale',
        ),
        migrations.RemoveField(
            model_name='mouvementcaisse',
            name='type_caisse',
        ),
        migrations.RemoveField(
            model_name='mouvementcaisse',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='cloture_par',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='ouvert_par',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='succursale',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='type_caisse',
        ),
        migrations.RemoveField(
            model_name='typecaisse',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='typecaisse',
            name='succursale',
        ),
        migrations.DeleteModel(
            name='DetailMouvementCaisse',
        ),
        migrations.DeleteModel(
            name='EcartCaisse',
        ),
        migrations.DeleteModel(
            name='MouvementCaisse',
        ),
        migrations.DeleteModel(
            name='SessionCaisse',
        ),
        migrations.DeleteModel(
            name='TypeCaisse',
        ),
]


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_session_caisse'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=STATE_OPS,
            database_operations=[],
        ),
        migrations.RunPython(_content_types_to_caisse, _content_types_to_stock),
    ]
