# Generated by Django 5.2.11 on 2026-07-02 05:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def _column_names(connection, table_name):
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    names = set()
    for column in description:
        names.add(getattr(column, 'name', column[0]))
    return names


def _ensure_field(schema_editor, model, field_name):
    table = model._meta.db_table
    if table not in set(schema_editor.connection.introspection.table_names()):
        return
    field = model._meta.get_field(field_name)
    columns = _column_names(schema_editor.connection, table)
    if field.column not in columns:
        schema_editor.add_field(model, field)


def apply_currency_schema(apps, schema_editor):
    field_map = {
        'DetteClient': ('devise_reference', 'montant_reference', 'taux_change'),
        'LigneEntree': ('devise_reference', 'montant_reference', 'taux_change'),
        'LigneSortie': ('devise_reference', 'montant_reference', 'taux_change'),
        'Sortie': ('devise_reference',),
    }
    for model_name, field_names in field_map.items():
        model = apps.get_model('stock', model_name)
        for field_name in field_names:
            _ensure_field(schema_editor, model, field_name)

    TauxChange = apps.get_model('stock', 'TauxChange')
    tables = set(schema_editor.connection.introspection.table_names())
    if TauxChange._meta.db_table not in tables:
        schema_editor.create_model(TauxChange)


STATE_OPERATIONS = [
    migrations.AddField(
        model_name='detteclient',
        name='devise_reference',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dettes_reference', to='stock.devise'),
    ),
    migrations.AddField(
        model_name='detteclient',
        name='montant_reference',
        field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14),
    ),
    migrations.AddField(
        model_name='detteclient',
        name='taux_change',
        field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
    ),
    migrations.AddField(
        model_name='ligneentree',
        name='devise_reference',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ligneentrees_reference', to='stock.devise'),
    ),
    migrations.AddField(
        model_name='ligneentree',
        name='montant_reference',
        field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14),
    ),
    migrations.AddField(
        model_name='ligneentree',
        name='taux_change',
        field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
    ),
    migrations.AddField(
        model_name='lignesortie',
        name='devise_reference',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignesorties_reference', to='stock.devise'),
    ),
    migrations.AddField(
        model_name='lignesortie',
        name='montant_reference',
        field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14),
    ),
    migrations.AddField(
        model_name='lignesortie',
        name='taux_change',
        field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
    ),
    migrations.AddField(
        model_name='sortie',
        name='devise_reference',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorties_reference', to='stock.devise'),
    ),
    migrations.CreateModel(
        name='TauxChange',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('taux', models.DecimalField(decimal_places=8, max_digits=20)),
            ('date_application', models.DateTimeField(default=django.utils.timezone.now)),
            ('is_active', models.BooleanField(default=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taux_change_crees', to=settings.AUTH_USER_MODEL)),
            ('devise_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_entrants', to='stock.devise')),
            ('devise_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_sortants', to='stock.devise')),
            ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_change', to='stock.entreprise')),
        ],
        options={
            'verbose_name': 'Taux de change',
            'verbose_name_plural': 'Taux de change',
            'ordering': ['-date_application', '-id'],
            'indexes': [
                models.Index(fields=['entreprise_id', 'is_active'], name='stock_tauxc_entrepr_a27464_idx'),
                models.Index(fields=['entreprise_id', 'devise_source_id', 'devise_cible_id'], name='stock_tauxc_entrepr_29e336_idx'),
                models.Index(fields=['entreprise_id', 'date_application'], name='stock_tauxc_entrepr_d4aa16_idx'),
            ],
        },
    ),
]


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('stock', '0030_entreprise_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=STATE_OPERATIONS,
        ),
        migrations.RunPython(apply_currency_schema, migrations.RunPython.noop),
    ]
