# Generated by Django 5.2.11 on 2026-06-28 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_currency_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tauxchange',
            new_name='stock_tauxc_entrepr_a27464_idx',
            old_name='stock_tauxc_entrepr_0d4a67_idx',
        ),
        migrations.RenameIndex(
            model_name='tauxchange',
            new_name='stock_tauxc_entrepr_29e336_idx',
            old_name='stock_tauxc_entrepr_4aa17d_idx',
        ),
        migrations.RenameIndex(
            model_name='tauxchange',
            new_name='stock_tauxc_entrepr_d4aa16_idx',
            old_name='stock_tauxc_entrepr_77d803_idx',
        ),
        migrations.AlterField(
            model_name='tauxchange',
            name='date_application',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
