# Generated by Django 5.2.11 on 2026-06-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_sortie_client_history_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sortie',
            new_name='stock_sorti_client__36a5f7_idx',
            old_name='stock_sortie_client_hist_idx',
        ),
    ]
