# Generated by Django 5.2.11 on 2026-07-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_code_barres_article'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='codebarresarticle',
            new_name='stock_codeb_entrepr_2683ca_idx',
            old_name='stock_codeb_entrepr_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='codebarresarticle',
            new_name='stock_codeb_entrepr_5146c9_idx',
            old_name='stock_codeb_entrepr_4c9e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='codebarresarticle',
            new_name='stock_codeb_article_b390e8_idx',
            old_name='stock_codeb_article_7b3f8e_idx',
        ),
    ]
