# Generated by Django 5.2.11 on 2026-07-14 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_rename_stock_codeb_entrepr_8a1f2d_idx_stock_codeb_entrepr_2683ca_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=32)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('observations', models.TextField(blank=True, default='')),
                ('commentaires', models.TextField(blank=True, default='')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('OUVERTE', 'Ouverte'), ('EN_PREPARATION', 'En préparation'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée'), ('CLOTUREE', 'Clôturée')], default='BROUILLON', max_length=32)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_rejet', models.DateTimeField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, default='')),
                ('archived', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='stock.entreprise')),
                ('rejete_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_rejetees', to=settings.AUTH_USER_MODEL)),
                ('succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='stock.succursale')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réquisition',
                'verbose_name_plural': 'Réquisitions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('ancien_statut', models.CharField(blank=True, default='', max_length=32)),
                ('nouveau_statut', models.CharField(blank=True, default='', max_length=32)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='stock.requisition')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_historique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('ARTICLE', 'Article existant'), ('LIBRE', 'Ligne libre')], default='ARTICLE', max_length=16)),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('unite', models.CharField(blank=True, default='', max_length=100)),
                ('prix_estime', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('prix_source', models.CharField(choices=[('DERNIER_ACHAT', "Dernier prix d'achat"), ('MANUEL', 'Saisie manuelle')], default='MANUEL', max_length=20)),
                ('remarque', models.TextField(blank=True, default='')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('statut_stock', models.CharField(blank=True, default='', max_length=32)),
                ('stock_actuel', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_requisition', to='stock.article')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.requisition')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['entreprise_id', 'statut'], name='stock_requi_entrepr_529811_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_requi_entrepr_8dc5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['entreprise_id', 'priorite'], name='stock_requi_entrepr_20030b_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['entreprise_id', 'cree_par_id'], name='stock_requi_entrepr_afcce3_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['entreprise_id', 'date_creation'], name='stock_requi_entrepr_e6b559_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisition',
            constraint=models.UniqueConstraint(fields=('entreprise', 'numero'), name='uniq_requisition_entreprise_numero'),
        ),
        migrations.AddIndex(
            model_name='requisitionhistorique',
            index=models.Index(fields=['requisition_id', 'date_action'], name='stock_requi_requisi_a84f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionligne',
            index=models.Index(fields=['requisition_id', 'ordre'], name='stock_requi_requisi_dba78b_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionligne',
            index=models.Index(fields=['requisition_id', 'article_id'], name='stock_requi_requisi_95ed46_idx'),
        ),
    ]
