# Generated by Django 5.2.11 on 2026-07-14 18:28

from decimal import Decimal
from django.db import migrations, models


def backfill_dernier_prix(apps, schema_editor):
    InventaireLigne = apps.get_model('stock', 'InventaireLigne')
    LigneEntree = apps.get_model('stock', 'LigneEntree')
    for ligne in InventaireLigne.objects.all().iterator():
        last = (
            LigneEntree.objects.filter(article_id=ligne.article_id)
            .order_by('-date_entree', '-id')
            .values_list('prix_unitaire', flat=True)
            .first()
        )
        pu = Decimal(str(last or 0))
        if ligne.dernier_prix_unitaire != pu:
            ligne.dernier_prix_unitaire = pu
            ligne.save(update_fields=['dernier_prix_unitaire'])


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_requisition_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaireligne',
            name='dernier_prix_unitaire',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text="Dernier prix unitaire d'achat figé à la création des lignes d'inventaire.", max_digits=14),
        ),
        migrations.RunPython(backfill_dernier_prix, migrations.RunPython.noop),
    ]
