# Generated by Django 5.2.11 on 2026-07-16 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_inventaire_valorisation_pu'),
    ]

    operations = [
        migrations.AddField(
            model_name='entree',
            name='source_requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvisionnements', to='stock.requisition'),
        ),
        migrations.AddField(
            model_name='entree',
            name='source_requisition_numero',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='requisition',
            name='transformation_status',
            field=models.CharField(choices=[('NON_TRANSFORMEE', 'Non transformée'), ('TRANSFORMEE', 'Transformée en approvisionnement')], default='NON_TRANSFORMEE', max_length=32),
        ),
        migrations.AddField(
            model_name='requisition',
            name='transformed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionligne',
            name='conditionnement',
            field=models.ForeignKey(blank=True, help_text="Conditionnement d'achat (quantité exprimée dans ce packing).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_requisition', to='stock.conditionnementarticle'),
        ),
        migrations.AlterField(
            model_name='requisitionligne',
            name='quantite',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Quantité à commander dans le conditionnement choisi.', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='entree',
            index=models.Index(fields=['source_requisition_id'], name='stock_entre_source__cb17d2_idx'),
        ),
    ]
