# Generated by Django 5.2.11 on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_requisition_to_approvisionnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='devise',
            field=models.ForeignKey(
                blank=True,
                help_text='Devise retenue pour les prix estimatifs de la réquisition. Les documents historiques sans devise utilisent la devise principale de l’entreprise.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='requisitions',
                to='stock.devise',
            ),
        ),
    ]
