# Generated by Django 5.2.11 on 2026-09-25 13:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0046_remove_dette_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliententreprise',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Priorité dans les rapports pour ce client dans cette entreprise.', verbose_name='Client spécial'),
        ),
        migrations.CreateModel(
            name='DettesClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=5, max_digits=14)),
                ('paye', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14)),
                ('reste', models.DecimalField(decimal_places=5, max_digits=14)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ENCOURS', 'En cours'), ('TERMINE', 'Terminé')], default='ENCOURS', max_length=20)),
                ('sortie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dette_client', to='stock.sortie')),
            ],
            options={
                'verbose_name': 'Dette client',
                'verbose_name_plural': 'Dettes clients',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaiementDettesClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=5, max_digits=14)),
                ('date', models.DateField()),
                ('dettes_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='stock.dettesclients')),
            ],
            options={
                'verbose_name': 'Paiement dette client',
                'verbose_name_plural': 'Paiements dettes clients',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dettesclients',
            index=models.Index(fields=['date'], name='stock_dette_date_0965c0_idx'),
        ),
        migrations.AddIndex(
            model_name='dettesclients',
            index=models.Index(fields=['status'], name='stock_dette_status_ee0840_idx'),
        ),
        migrations.AddIndex(
            model_name='dettesclients',
            index=models.Index(fields=['date', 'status'], name='stock_dette_date_53d584_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementdettesclients',
            index=models.Index(fields=['date'], name='stock_paiem_date_3bc5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementdettesclients',
            index=models.Index(fields=['dettes_clients', 'date'], name='stock_paiem_dettes__c82807_idx'),
        ),
    ]
