# Generated by Django 5.2.11 on 2026-09-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_dettes_clients_perf_timestamps'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dettesclients',
            new_name='stock_dette_status_6c1738_idx',
            old_name='stock_dette_status_2f8a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='paiementdettesclients',
            new_name='stock_paiem_id_b2a244_idx',
            old_name='stock_paiem_id_desc_idx',
        ),
    ]
