# Generated by Django 5.2.11 on 2026-10-01 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0051_sortie_retire_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairesession',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventairesession',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventairesession',
            name='journal_annulation',
            field=models.JSONField(blank=True, help_text='Détail des mouvements annulés et des quantités restaurées (audit).', null=True),
        ),
        migrations.AddField(
            model_name='inventairesession',
            name='motif_annulation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventairesession',
            name='validation_annulee',
            field=models.BooleanField(default=False, help_text="True si l'inventaire avait été validé puis ses ajustements annulés."),
        ),
    ]
