# Generated by Django 5.2.11 on 2026-07-06 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnvoiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_email', models.CharField(db_index=True, max_length=32)),
                ('destinataire', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(db_index=True, default='prepare', max_length=20)),
                ('code_erreur', models.CharField(blank=True, max_length=64)),
                ('details', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Journal envoi e-mail',
                'verbose_name_plural': 'Journal envois e-mail',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='inscription_utilisa_7bd51d_idx',
            old_name='inscription_utilisa_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='inscription_expire__6f38ca_idx',
            old_name='inscription_expire__4c9b1a_idx',
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='email_cible',
            field=models.EmailField(help_text='Adresse visée au moment de la génération (utile si changement en attente).', max_length=254),
        ),
        migrations.AddField(
            model_name='emailenvoilog',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailenvoilog',
            index=models.Index(fields=['utilisateur', 'type_email', '-cree_le'], name='inscription_utilisa_e8500d_idx'),
        ),
        migrations.AddIndex(
            model_name='emailenvoilog',
            index=models.Index(fields=['destinataire', 'type_email', '-cree_le'], name='inscription_destina_698c66_idx'),
        ),
    ]
