# Generated by Django 5.2.11 on 2026-07-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_workspaceactivationtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspaceactivationtoken',
            new_name='inscription_utilisa_06fb9d_idx',
            old_name='inscription_utilisa_8f0a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceactivationtoken',
            new_name='inscription_expire__01b0d3_idx',
            old_name='inscription_expire__a1b2c3_idx',
        ),
    ]
