# Generated by Django 5.2.11 on 2026-06-29 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0034_rename_stock_sortie_client_hist_idx_stock_sorti_client__36a5f7_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormuleAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_annuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='USD', max_length=3)),
                ('duree_essai_jours', models.PositiveIntegerField(default=0, help_text="Durée d'essai automatique à la création d'entreprise (0 = pas d'essai auto).")),
                ('fonctionnalites', models.JSONField(blank=True, default=dict, help_text='Drapeaux de fonctionnalités autorisées pour cette formule.')),
                ('limites', models.JSONField(blank=True, default=dict, help_text='Limites quantitatives (utilisateurs, succursales, etc.).')),
                ('est_visible_catalogue', models.BooleanField(default=True, help_text='False pour la formule essai interne.')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Formule d'abonnement",
                'verbose_name_plural': "Formules d'abonnement",
                'ordering': ['ordre_affichage', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemandeInstallationPrivee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contact', models.CharField(max_length=200)),
                ('email_contact', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', "En cours d'étude"), ('cloturee', 'Clôturée'), ('refusee', 'Refusée')], default='nouvelle', max_length=20)),
                ('notes_internes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_installation_privee', to='stock.entreprise')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_installation_privee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande installation privée',
                'verbose_name_plural': 'Demandes installation privée',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('essai', 'Essai gratuit'), ('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('periode', models.CharField(choices=[('essai', 'Essai'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='mensuel', max_length=20)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('renouvellement_auto', models.BooleanField(default=False)),
                ('activation_manuelle', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('est_courant', models.BooleanField(default=False, help_text='Un seul abonnement courant par entreprise.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_actives', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='stock.entreprise')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='abonnements.formuleabonnement')),
            ],
            options={
                'verbose_name': 'Abonnement entreprise',
                'verbose_name_plural': 'Abonnements entreprise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalActivationLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('essai_demarre', 'Essai démarré'), ('demande_abonnement', "Demande d'abonnement"), ('activation_manuelle', 'Activation manuelle'), ('activation_paiement', 'Activation via paiement'), ('expiration', 'Expiration'), ('suspension', 'Suspension'), ('reactivation', 'Réactivation'), ('changement_plan', 'Changement de plan'), ('prolongation_essai', 'Prolongation essai')], max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='abonnements.abonnemententreprise')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_licence', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_licences', to='stock.entreprise')),
            ],
            options={
                'verbose_name': 'Journal activation licence',
                'verbose_name_plural': 'Journal activations licence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='USD', max_length=3)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('fournisseur', models.CharField(choices=[('manuel', 'Activation manuelle'), ('maisha_pay', 'Maisha Pay'), ('flexpay', 'FlexPay'), ('serdinate_pay', 'SerdinatePay')], default='manuel', max_length=30)),
                ('reference_externe', models.CharField(blank=True, max_length=255)),
                ('payload_gateway', models.JSONField(blank=True, default=dict)),
                ('confirme_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='abonnements.abonnemententreprise')),
                ('confirme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_abonnement_confirmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement abonnement',
                'verbose_name_plural': 'Paiements abonnement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='abonnemententreprise',
            index=models.Index(fields=['entreprise', 'est_courant'], name='abonnements_entrepr_d0e904_idx'),
        ),
        migrations.AddIndex(
            model_name='abonnemententreprise',
            index=models.Index(fields=['statut', 'date_fin'], name='abonnements_statut_8b0357_idx'),
        ),
    ]
