# Generated by Django 5.2.11 on 2026-07-04 17:28

import abonnements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_paiement_reference_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementabonnement',
            name='reference_interne',
            field=models.CharField(default=abonnements.models._generer_reference_paiement, editable=False, help_text='Référence unique UHAKIKAAPP transmise au gateway.', max_length=64, unique=True),
        ),
    ]
