# Generated by Django 5.2.11 on 2026-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0003_alter_paiementabonnement_reference_interne'),
    ]

    operations = [
        migrations.AddField(
            model_name='formuleabonnement',
            name='prix_a_vie',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix unique (paiement unique) pour la formule à vie.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='abonnemententreprise',
            name='periode',
            field=models.CharField(choices=[('essai', 'Essai'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('a_vie', 'À vie')], default='mensuel', max_length=20),
        ),
    ]
