# Generated by Django 5.2.11 on 2026-06-24 17:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


STATE_OPS = [
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('ouvert_le', models.DateTimeField()),
                ('cloture_le', models.DateTimeField(blank=True, null=True)),
                ('solde_ouverture', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14)),
                ('total_entrees', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14)),
                ('total_sorties', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14)),
                ('solde_theorique', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('montant_physique', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('ecart_montant', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE_EN_ATTENTE_VALIDATION', 'Clôturée en attente validation écart'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=40)),
                ('commentaire_cloture', models.TextField(blank=True, default='')),
                ('est_legacy', models.BooleanField(default=False, help_text="Session créée par migration pour rattacher l'historique existant.")),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_caisse_cloturees', to=settings.AUTH_USER_MODEL)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to='stock.devise')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_caisse', to='stock.entreprise')),
                ('ouvert_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_caisse_ouvertes', to=settings.AUTH_USER_MODEL)),
                ('succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_caisse', to='stock.succursale')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'db_table': 'stock_sessioncaisse',
                'ordering': ['-ouvert_le', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=5, max_digits=12)),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('motif', models.TextField(blank=True, default='', help_text='Libellé / motif du mouvement.')),
                ('moyen', models.CharField(blank=True, help_text='Ex. : Cash, Mobile Money, Chèque (optionnel).', max_length=30, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_piece', models.CharField(blank=True, default='', max_length=100)),
                ('categorie', models.CharField(blank=True, choices=[('VENTE', 'Vente comptant'), ('PAIEMENT_DETTE', 'Paiement dette client'), ('APPROVISIONNEMENT', 'Approvisionnement payé cash'), ('DEPENSE', 'Dépense'), ('ENTREE_MANUELLE', 'Entrée manuelle'), ('SORTIE_MANUELLE', 'Sortie manuelle'), ('AJUSTEMENT_SURPLUS_CAISSE', 'Ajustement surplus caisse'), ('AJUSTEMENT_PERTE_CAISSE', 'Ajustement perte caisse'), ('AUTRE', 'Autre')], default='AUTRE', max_length=40)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse', to='stock.devise')),
                ('entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvement_caisse', to='stock.entree')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse', to='stock.entreprise')),
                ('sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvement_caisse', to='stock.sortie')),
                ('succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse', to='stock.succursale')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse_effectues', to=settings.AUTH_USER_MODEL)),
                ('session_caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='caisse.sessioncaisse')),
            ],
            options={
                'db_table': 'stock_mouvementcaisse',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EcartCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecart', models.CharField(choices=[('SURPLUS', 'Surplus'), ('PERTE', 'Perte')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=5, help_text="Montant absolu de l'écart", max_digits=14)),
                ('statut', models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='EN_ATTENTE_VALIDATION', max_length=30)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('declare_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecarts_caisse_declares', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecarts_caisse_valides', to=settings.AUTH_USER_MODEL)),
                ('mouvement_ajustement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecart_source', to='caisse.mouvementcaisse')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecart', to='caisse.sessioncaisse')),
            ],
            options={
                'verbose_name': 'Écart de caisse',
                'verbose_name_plural': 'Écarts de caisse',
                'db_table': 'stock_ecartcaisse',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='TypeCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='types_caisse/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_caisse', to='stock.entreprise')),
                ('succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types_caisse', to='stock.succursale')),
            ],
            options={
                'verbose_name': 'Type de caisse',
                'verbose_name_plural': 'Types de caisse',
                'db_table': 'stock_typecaisse',
                'ordering': ['entreprise_id', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='type_caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to='caisse.typecaisse'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='type_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='caisse.typecaisse'),
        ),
        migrations.CreateModel(
            name='DetailMouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=5, max_digits=12)),
                ('motif_explicite', models.TextField(blank=True, default='', help_text='Si pas de type_caisse, motif obligatoire ou généré automatiquement.')),
                ('reference_piece', models.CharField(blank=True, default='', max_length=100)),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='caisse.mouvementcaisse')),
                ('type_caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_mouvements', to='caisse.typecaisse')),
            ],
            options={
                'verbose_name': 'Détail mouvement caisse',
                'verbose_name_plural': 'Détails mouvements caisse',
                'db_table': 'stock_detailmouvementcaisse',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='typecaisse',
            index=models.Index(fields=['entreprise_id'], name='stock_typec_entrepr_4f8295_idx'),
        ),
        migrations.AddIndex(
            model_name='typecaisse',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_typec_entrepr_abb535_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncaisse',
            index=models.Index(fields=['entreprise_id', 'succursale_id', 'statut'], name='stock_sessi_entrepr_3658b0_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncaisse',
            index=models.Index(fields=['type_caisse_id', 'devise_id', 'statut'], name='stock_sessi_type_ca_766535_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['entreprise_id'], name='stock_mouve_entrepr_bd2459_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['succursale_id'], name='stock_mouve_succurs_0d3ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['entreprise_id', 'succursale_id'], name='stock_mouve_entrepr_c4f4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['content_type', 'object_id'], name='stock_mouve_content_354bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['session_caisse_id', 'date'], name='stock_mouve_session_a1deb6_idx'),
        ),
    ]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stock', '0029_move_caisse_to_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=STATE_OPS,
            database_operations=[],
        ),
    ]
