# Generated by Django 5.2.11 on 2026-06-24 17:38

import django.db.models.deletion
from django.db import migrations, models


def migrer_caisses_legacy(apps, schema_editor):
    TypeCaisse = apps.get_model('caisse', 'TypeCaisse')
    MouvementCaisse = apps.get_model('caisse', 'MouvementCaisse')
    SessionCaisse = apps.get_model('caisse', 'SessionCaisse')
    Entreprise = apps.get_model('stock', 'Entreprise')
    Succursale = apps.get_model('stock', 'Succursale')
    Devise = apps.get_model('stock', 'Devise')

    CAISSE_NOM = 'Caisse principale'
    CAISSE_LIBELLE = 'Caisse cash physique'
    CAISSE_CODE = 'CASH'

    def devise_principale(ent_id):
        return Devise.objects.filter(entreprise_id=ent_id, est_principal=True).first()

    def ensure_default(ent_id, succursale_id=None):
        qs = TypeCaisse.objects.filter(
            entreprise_id=ent_id,
            est_defaut=True,
            code_type=CAISSE_CODE,
        )
        if succursale_id is not None:
            qs = qs.filter(succursale_id=succursale_id)
        else:
            qs = qs.filter(succursale_id__isnull=True)
        tc = qs.first()
        if tc:
            updates = {}
            if not (tc.nom or '').strip():
                updates['nom'] = CAISSE_NOM
            if not (tc.libelle or '').strip():
                updates['libelle'] = CAISSE_LIBELLE
            if not tc.devise_id:
                dev = devise_principale(ent_id)
                if dev:
                    updates['devise_id'] = dev.id
            if updates:
                TypeCaisse.objects.filter(pk=tc.pk).update(**updates)
            return TypeCaisse.objects.get(pk=tc.pk)

        existing = TypeCaisse.objects.filter(
            entreprise_id=ent_id,
            succursale_id=succursale_id,
        ).order_by('id').first()
        if existing:
            TypeCaisse.objects.filter(pk=existing.pk).update(
                nom=existing.nom or CAISSE_NOM,
                libelle=existing.libelle or CAISSE_LIBELLE,
                code_type=CAISSE_CODE,
                est_defaut=True,
                devise_id=existing.devise_id or (devise_principale(ent_id).id if devise_principale(ent_id) else None),
                is_active=True,
            )
            return TypeCaisse.objects.get(pk=existing.pk)

        dev = devise_principale(ent_id)
        return TypeCaisse.objects.create(
            nom=CAISSE_NOM,
            libelle=CAISSE_LIBELLE,
            code_type=CAISSE_CODE,
            description='Caisse cash physique par défaut (migration).',
            entreprise_id=ent_id,
            succursale_id=succursale_id,
            devise_id=dev.id if dev else None,
            is_active=True,
            est_defaut=True,
        )

    for tc in TypeCaisse.objects.all().iterator():
        updates = {}
        if not (tc.nom or '').strip():
            updates['nom'] = tc.libelle or CAISSE_NOM
        if not (tc.libelle or '').strip():
            updates['libelle'] = tc.nom or CAISSE_LIBELLE
        if not tc.code_type:
            updates['code_type'] = CAISSE_CODE
        if not tc.devise_id:
            dev = devise_principale(tc.entreprise_id)
            if dev:
                updates['devise_id'] = dev.id
        if updates:
            TypeCaisse.objects.filter(pk=tc.pk).update(**updates)

    for ent in Entreprise.objects.all().iterator():
        default_ent = ensure_default(ent.id, None)
        for succ in Succursale.objects.filter(entreprise_id=ent.id).iterator():
            default_branch = ensure_default(ent.id, succ.id)
            MouvementCaisse.objects.filter(
                entreprise_id=ent.id,
                succursale_id=succ.id,
                type_caisse_id__isnull=True,
            ).update(type_caisse_id=default_branch.id)
            SessionCaisse.objects.filter(
                entreprise_id=ent.id,
                succursale_id=succ.id,
                type_caisse_id__isnull=True,
            ).update(type_caisse_id=default_branch.id)

        MouvementCaisse.objects.filter(
            entreprise_id=ent.id,
            type_caisse_id__isnull=True,
        ).update(type_caisse_id=default_ent.id)
        SessionCaisse.objects.filter(
            entreprise_id=ent.id,
            type_caisse_id__isnull=True,
        ).update(type_caisse_id=default_ent.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_move_caisse_to_app'),
        ('stock', '0029_move_caisse_to_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecaisse',
            options={'ordering': ['entreprise_id', 'nom', 'libelle'], 'verbose_name': 'Caisse', 'verbose_name_plural': 'Caisses'},
        ),
        migrations.AddField(
            model_name='typecaisse',
            name='code_type',
            field=models.CharField(choices=[('CASH', 'Caisse cash physique'), ('BANQUE', 'Banque'), ('AIRTEL_MONEY', 'Airtel Money'), ('MPESA', 'M-Pesa'), ('ORANGE_MONEY', 'Orange Money'), ('MOBILE_MONEY', 'Mobile Money'), ('AUTRE', 'Autre')], default='CASH', help_text='Catégorie de caisse (CASH, BANQUE, AIRTEL_MONEY, …).', max_length=20),
        ),
        migrations.AddField(
            model_name='typecaisse',
            name='devise',
            field=models.ForeignKey(blank=True, help_text='Devise principale de cette caisse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caisses', to='stock.devise'),
        ),
        migrations.AddField(
            model_name='typecaisse',
            name='est_defaut',
            field=models.BooleanField(default=False, help_text="Caisse cash physique par défaut pour l'entreprise / agence."),
        ),
        migrations.AddField(
            model_name='typecaisse',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='typecaisse',
            index=models.Index(fields=['entreprise_id', 'est_defaut'], name='stock_typec_entrepr_00f802_idx'),
        ),
        migrations.AddIndex(
            model_name='typecaisse',
            index=models.Index(fields=['entreprise_id', 'code_type'], name='stock_typec_entrepr_854d9d_idx'),
        ),
        migrations.RunPython(migrer_caisses_legacy, noop_reverse),
    ]
