# Generated by Django 5.2.11 on 2026-07-02 05:21

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


def _column_names(connection, table_name):
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    names = set()
    for column in description:
        names.add(getattr(column, 'name', column[0]))
    return names


def _ensure_field(schema_editor, model, field_name):
    table = model._meta.db_table
    if table not in set(schema_editor.connection.introspection.table_names()):
        return
    field = model._meta.get_field(field_name)
    columns = _column_names(schema_editor.connection, table)
    if field.column not in columns:
        schema_editor.add_field(model, field)


def apply_mouvement_caisse_currency_fields(apps, schema_editor):
    MouvementCaisse = apps.get_model('caisse', 'MouvementCaisse')
    for field_name in ('devise_reference', 'montant_reference', 'taux_change'):
        _ensure_field(schema_editor, MouvementCaisse, field_name)


STATE_OPERATIONS = [
    migrations.AddField(
        model_name='mouvementcaisse',
        name='devise_reference',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_caisse_reference', to='stock.devise'),
    ),
    migrations.AddField(
        model_name='mouvementcaisse',
        name='montant_reference',
        field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14),
    ),
    migrations.AddField(
        model_name='mouvementcaisse',
        name='taux_change',
        field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
    ),
]


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('caisse', '0002_type_caisse_multi_caisse'),
        ('stock', '0031_detteclient_devise_reference_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=STATE_OPERATIONS,
        ),
        migrations.RunPython(apply_mouvement_caisse_currency_fields, migrations.RunPython.noop),
    ]
