# Generated by Django 5.2.11 on 2026-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_remove_paiement_dette_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='montant_applique',
            field=models.DecimalField(blank=True, decimal_places=5, help_text="Montant imputé sur l'objet lié dans la devise métier de cet objet.", max_digits=14, null=True),
        ),
    ]
