# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("stock", "0017_fournisseur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lot",
            name="fournisseur",
        ),
        migrations.AddField(
            model_name="lot",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lots_en_transit",
                to="stock.fournisseur",
            ),
        ),
    ]
