# Generated by Django 5.2.11 on 2026-03-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_lot_fournisseur_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fraislot',
            new_name='order_frais_entrepr_cf6b25_idx',
            old_name='order_fraislots_entreprise_lot_type_frais_idx',
        ),
        migrations.RenameIndex(
            model_name='lot',
            new_name='order_lot_entrepr_b05243_idx',
            old_name='order_lot_entreprise_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='lot',
            new_name='order_lot_entrepr_986a9c_idx',
            old_name='order_lot_entreprise_fournisseur_idx',
        ),
        migrations.RenameIndex(
            model_name='lot',
            new_name='order_lot_entrepr_3fc7fe_idx',
            old_name='order_lot_entreprise_date_expedition_idx',
        ),
        migrations.RenameIndex(
            model_name='lotitem',
            new_name='order_lotit_entrepr_76e0c5_idx',
            old_name='order_lotitem_entreprise_lot_article_idx',
        ),
    ]
