# Generated by Django 5.2.11 on 2026-03-27 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_commande_commandeitem_commanderesponse'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commande',
            new_name='order_comma_entrepr_c8fef6_idx',
            old_name='order_commande_entreprise_client_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='commande',
            new_name='order_comma_entrepr_6475a3_idx',
            old_name='order_commande_entreprise_created_idx',
        ),
        migrations.RenameIndex(
            model_name='commande',
            new_name='order_comma_entrepr_a22c06_idx',
            old_name='order_commande_entreprise_statut_created_idx',
        ),
        migrations.RenameIndex(
            model_name='commandeitem',
            new_name='order_comma_command_1a29b4_idx',
            old_name='order_commandeitem_commande_article_idx',
        ),
        migrations.RenameIndex(
            model_name='commanderesponse',
            new_name='order_comma_command_b24409_idx',
            old_name='order_commande_resp_commande_created_idx',
        ),
        migrations.RenameIndex(
            model_name='fournisseur',
            new_name='order_fourn_entrepr_40c3fc_idx',
            old_name='order_fournisseur_entreprise_nom_idx',
        ),
        migrations.RenameIndex(
            model_name='fournisseur',
            new_name='order_fourn_entrepr_7944ce_idx',
            old_name='order_fournisseur_entreprise_active_idx',
        ),
        migrations.RenameIndex(
            model_name='fournisseur',
            new_name='order_fourn_entrepr_464367_idx',
            old_name='order_fournisseur_entreprise_code_idx',
        ),
        migrations.RenameIndex(
            model_name='fournisseur',
            new_name='order_fourn_entrepr_e4f51b_idx',
            old_name='order_fournisseur_entreprise_created_idx',
        ),
    ]
