# Generated by Django 5.2.11 on 2026-04-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_clear_entree_description_lot_closure'),
        ('stock', '0022_alter_mouvementcaisse_motif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='sortie_livraison',
            field=models.OneToOneField(blank=True, help_text='Sortie de stock créée automatiquement lors du passage au statut « livrée ».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_livraison', to='stock.sortie'),
        ),
    ]
