# Generated by Django 5.2.11 on 2026-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_decimal_item_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeitem',
            name='quantite',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fraislot',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lotitem',
            name='prix_achat_unitaire',
            field=models.DecimalField(decimal_places=5, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lotitem',
            name='quantite',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
